import React, { useEffect, useState } from "react";
import "./AllocationMatrix.css";

function AllocationMatrix() {
  const [allocations, setAllocations] = useState([]);
  const [filteredAllocations, setFilteredAllocations] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const [search, setSearch] = useState("");
  const [discountFilter, setDiscountFilter] = useState("all");

  useEffect(() => {
    fetch("/data/optimized_discount_assignments.csv")
      .then((response) => {
        if (!response.ok) {
          throw new Error(
            "Unable to load optimized discount assignments."
          );
        }

        return response.text();
      })
      .then((text) => {
        const rows = parseCSV(text);

        setAllocations(rows);
        setFilteredAllocations(rows);
        setLoading(false);
      })
      .catch((err) => {
        console.error(err);
        setError(err.message);
        setLoading(false);
      });
  }, []);

  // --------------------------------------------------
  // Simple CSV parser
  // --------------------------------------------------

  const parseCSV = (text) => {
    const lines = text
      .trim()
      .split(/\r?\n/)
      .filter((line) => line.trim() !== "");

    if (lines.length < 2) {
      return [];
    }

    const headers = lines[0]
      .split(",")
      .map((header) => header.trim());

    return lines.slice(1).map((line) => {
      const values = line.split(",");

      const row = {};

      headers.forEach((header, index) => {
        row[header] = values[index]?.trim() || "";
      });

      return row;
    });
  };

  // --------------------------------------------------
  // Filtering
  // --------------------------------------------------

  useEffect(() => {
    let result = [...allocations];

    if (search.trim() !== "") {
      result = result.filter((customer) =>
        String(customer.customer_id)
          .toLowerCase()
          .includes(search.toLowerCase())
      );
    }

    if (discountFilter !== "all") {
      result = result.filter(
        (customer) =>
          Number(
            customer.optimal_discount ??
            customer.discount ??
            0
          ) === Number(discountFilter)
      );
    }

    setFilteredAllocations(result);
  }, [search, discountFilter, allocations]);

  // --------------------------------------------------
  // Loading
  // --------------------------------------------------

  if (loading) {
    return (
      <section className="allocation-page">
        <div className="allocation-container">
          <div className="allocation-loading">
            Loading optimization results...
          </div>
        </div>
      </section>
    );
  }

  // --------------------------------------------------
  // Error
  // --------------------------------------------------

  if (error) {
    return (
      <section className="allocation-page">
        <div className="allocation-container">
          <div className="allocation-header">
            <span className="allocation-eyebrow">
              PRESCRIPTIVE OPTIMIZATION
            </span>

            <h1>Final Prescription</h1>

            <p>
              View the mathematically optimal discount
              allocation generated by the optimization model.
            </p>
          </div>

          <div className="allocation-error">
            <strong>Unable to load prescription data</strong>

            <p>{error}</p>

            <small>
              Make sure optimized_discount_assignments.csv
              exists inside frontend/public/data/.
            </small>
          </div>
        </div>
      </section>
    );
  }

  // --------------------------------------------------
  // Summary
  // --------------------------------------------------

  const totalCustomers = allocations.length;

  const allocatedCustomers = allocations.filter(
    (customer) =>
      Number(
        customer.optimal_discount ??
        customer.discount ??
        0
      ) > 0
  ).length;

  const totalRevenue = allocations.reduce(
    (sum, customer) =>
      sum +
      Number(
        customer.predicted_revenue ??
        customer.revenue ??
        0
      ),
    0
  );

  const totalCost = allocations.reduce(
    (sum, customer) =>
      sum +
      Number(
        customer.marketing_cost ??
        customer.discount_cost ??
        customer.cost ??
        0
      ),
    0
  );

  return (
    <section className="allocation-page">
      <div className="allocation-container">

        {/* HEADER */}

        <div className="allocation-header">

          <span className="allocation-eyebrow">
            PRESCRIPTIVE OPTIMIZATION
          </span>

          <h1>Final Prescription</h1>

          <p>
            Customer-level optimal discount allocation
            generated by the prescriptive optimization model.
          </p>

        </div>

        {/* SUMMARY CARDS */}

        <div className="allocation-summary">

          <div className="allocation-summary-card">
            <span>Total Customers</span>
            <strong>
              {totalCustomers.toLocaleString()}
            </strong>
          </div>

          <div className="allocation-summary-card">
            <span>Customers Allocated</span>
            <strong>
              {allocatedCustomers.toLocaleString()}
            </strong>
          </div>

          <div className="allocation-summary-card">
            <span>Predicted Revenue</span>
            <strong>
              ₹{totalRevenue.toFixed(2)}
            </strong>
          </div>

          <div className="allocation-summary-card">
            <span>Marketing Cost</span>
            <strong>
              ₹{totalCost.toFixed(2)}
            </strong>
          </div>

        </div>

        {/* FILTERS */}

        <div className="allocation-controls">

          <div className="search-box">

            <label>
              Search Customer
            </label>

            <input
              type="text"
              placeholder="Enter customer ID..."
              value={search}
              onChange={(event) =>
                setSearch(event.target.value)
              }
            />

          </div>

          <div className="discount-filter">

            <label>
              Optimal Discount
            </label>

            <select
              value={discountFilter}
              onChange={(event) =>
                setDiscountFilter(event.target.value)
              }
            >
              <option value="all">
                All Discounts
              </option>

              <option value="0">0%</option>
              <option value="5">5%</option>
              <option value="10">10%</option>
              <option value="15">15%</option>
              <option value="20">20%</option>
              <option value="25">25%</option>
              <option value="30">30%</option>
            </select>

          </div>

        </div>

        {/* TABLE */}

        <div className="allocation-table-card">

          <div className="table-header">

            <div>
              <h2>Allocation Matrix</h2>

              <p>
                {filteredAllocations.length.toLocaleString()}
                {" "}customers displayed
              </p>
            </div>

          </div>

          <div className="table-wrapper">

            <table>

              <thead>

                <tr>
                  <th>Customer ID</th>
                  <th>ITE</th>
                  <th>Optimal Discount</th>
                  <th>Predicted Revenue</th>
                  <th>Marketing Cost</th>
                </tr>

              </thead>

              <tbody>

                {filteredAllocations.length === 0 ? (

                  <tr>
                    <td
                      colSpan="5"
                      className="empty-table"
                    >
                      No customers found.
                    </td>
                  </tr>

                ) : (

                  filteredAllocations.map(
                    (customer, index) => {

                      const discount =
                        Number(
                          customer.optimal_discount ??
                          customer.discount ??
                          0
                        );

                      const revenue =
                        Number(
                          customer.predicted_revenue ??
                          customer.revenue ??
                          0
                        );

                      const cost =
                        Number(
                          customer.marketing_cost ??
                          customer.discount_cost ??
                          customer.cost ??
                          0
                        );

                      return (
                        <tr
                          key={
                            customer.customer_id ??
                            index
                          }
                        >

                          <td className="customer-id">
                            {customer.customer_id}
                          </td>

                          <td>
                            {customer.ite !== undefined
                              ? Number(
                                  customer.ite
                                ).toFixed(4)
                              : "—"}
                          </td>

                          <td>
                            <span
                              className={
                                discount > 0
                                  ? "discount-badge active"
                                  : "discount-badge"
                              }
                            >
                              {discount}%
                            </span>
                          </td>

                          <td>
                            ₹{revenue.toFixed(2)}
                          </td>

                          <td>
                            ₹{cost.toFixed(2)}
                          </td>

                        </tr>
                      );
                    }
                  )

                )}

              </tbody>

            </table>

          </div>

        </div>

      </div>
    </section>
  );
}

export default AllocationMatrix;